name: CI
#https://docs.github.com/en/actions/tutorials/build-and-test-code/net
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call: # allows cd.yml to trigger this and wait for it

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore
        run: dotnet restore NagerHolidays/NagerHolidays.sln

      - name: Build
        run: dotnet build NagerHolidays/NagerHolidays.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test NagerHolidays/NagerHolidays.sln --no-build --configuration Release --logger "console;verbosity=normal"
